/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EmiRouteImport } from './routes/emi'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as LoansIdRouteImport } from './routes/loans.$id'
import { Route as LoansNewRouteImport } from './routes/loans.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EmiRoute = EmiRouteImport.update({
  id: '/emi',
  path: '/emi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const LoansIdRoute = LoansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LoansRoute,
} as any)
const LoansNewRoute = LoansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LoansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/collection': typeof CollectionRoute
  '/customers': typeof CustomersRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/emi': typeof EmiRoute
  '/loans': typeof LoansRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/visits': typeof VisitsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/loans/new': typeof LoansNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/collection': typeof CollectionRoute
  '/customers': typeof CustomersRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/emi': typeof EmiRoute
  '/loans': typeof LoansRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/visits': typeof VisitsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/loans/new': typeof LoansNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/collection': typeof CollectionRoute
  '/customers': typeof CustomersRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/emi': typeof EmiRoute
  '/loans': typeof LoansRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/visits': typeof VisitsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/loans/new': typeof LoansNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/collection'
    | '/customers'
    | '/documents'
    | '/emi'
    | '/loans'
    | '/login'
    | '/profile'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/visits'
    | '/customers/$id'
    | '/loans/$id'
    | '/loans/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/collection'
    | '/customers'
    | '/documents'
    | '/emi'
    | '/loans'
    | '/login'
    | '/profile'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/visits'
    | '/customers/$id'
    | '/loans/$id'
    | '/loans/new'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/collection'
    | '/customers'
    | '/documents'
    | '/emi'
    | '/loans'
    | '/login'
    | '/profile'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/visits'
    | '/customers/$id'
    | '/loans/$id'
    | '/loans/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  CollectionRoute: typeof CollectionRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  EmiRoute: typeof EmiRoute
  LoansRoute: typeof LoansRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  VisitsRoute: typeof VisitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi': {
      id: '/emi'
      path: '/emi'
      fullPath: '/emi'
      preLoaderRoute: typeof EmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/loans/$id': {
      id: '/loans/$id'
      path: '/$id'
      fullPath: '/loans/$id'
      preLoaderRoute: typeof LoansIdRouteImport
      parentRoute: typeof LoansRoute
    }
    '/loans/new': {
      id: '/loans/new'
      path: '/new'
      fullPath: '/loans/new'
      preLoaderRoute: typeof LoansNewRouteImport
      parentRoute: typeof LoansRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface LoansRouteChildren {
  LoansIdRoute: typeof LoansIdRoute
  LoansNewRoute: typeof LoansNewRoute
}

const LoansRouteChildren: LoansRouteChildren = {
  LoansIdRoute: LoansIdRoute,
  LoansNewRoute: LoansNewRoute,
}

const LoansRouteWithChildren = LoansRoute._addFileChildren(LoansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  CollectionRoute: CollectionRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  EmiRoute: EmiRoute,
  LoansRoute: LoansRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReceiptsRoute: ReceiptsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  VisitsRoute: VisitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
